package main.components.appointement;

import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import main.controller.ContellerAppointment;
import main.controller.ControllerUser;
import main.model.ModelPatient;
import main.services.ServicePatient;
import main.services.ServiceRole;
import main.services.ServiceUser;

/**
 *
 * @author malco
 */
public class PanelForm extends javax.swing.JPanel {

    /**
     * Creates new form AppointementForm
     * @param commande_back
     * @param commande_createAppointment
     * @throws java.sql.SQLException
     */
    public PanelForm(ActionListener commande_back, ActionListener commande_createAppointment) throws SQLException {
        initComponents();
        init();
        initCommandeBack(commande_back);
        initCommandeCreateAppoitment(commande_createAppointment);
    }
    
    private void init() throws SQLException {
        ControllerUser userController = new ControllerUser();
        String[] doctorList = userController.getDoctors();
        
        for (String doctorList1 : doctorList) {
            choice_doctor.add(doctorList1);
        }
    }
    
    private void initCommandeBack(ActionListener commande_back) {
        btn_cancel.addActionListener(commande_back);
    }
    
    private void initCommandeCreateAppoitment(ActionListener commande_createAppointment) {
        btn_validate.addActionListener(commande_createAppointment);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        pFirstName = new javax.swing.JTextField();
        pLastName = new javax.swing.JTextField();
        pEmail = new javax.swing.JTextField();
        pTelephone = new javax.swing.JTextField();
        pBirthDate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        choice_doctor = new java.awt.Choice();
        btn_cancel = new assets.swing.Button();
        btn_validate = new assets.swing.Button();
        pDate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pHour = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Créer un nouveau rendez-vous");

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 20));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Patient");

        pFirstName.setBackground(new java.awt.Color(242, 242, 242));
        pFirstName.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        pFirstName.setText("Nom*");
        pFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pFirstNameActionPerformed(evt);
            }
        });

        pLastName.setBackground(new java.awt.Color(242, 242, 242));
        pLastName.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        pLastName.setText("Prénom*");
        pLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pLastNameActionPerformed(evt);
            }
        });

        pEmail.setBackground(new java.awt.Color(242, 242, 242));
        pEmail.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        pEmail.setText("E-mail*");
        pEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pEmailActionPerformed(evt);
            }
        });

        pTelephone.setBackground(new java.awt.Color(242, 242, 242));
        pTelephone.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        pTelephone.setText("Téléphone*");
        pTelephone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pTelephoneActionPerformed(evt);
            }
        });

        pBirthDate.setBackground(new java.awt.Color(242, 242, 242));
        pBirthDate.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        pBirthDate.setText("Naissance*(12/07/2002)");
        pBirthDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pBirthDateActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Dorteur");

        choice_doctor.setBackground(new java.awt.Color(242, 242, 242));
        choice_doctor.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        btn_cancel.setBackground(new java.awt.Color(242, 242, 242));
        btn_cancel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_cancel.setText("Retour");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        btn_validate.setBackground(new java.awt.Color(35, 166, 97));
        btn_validate.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_validate.setForeground(new java.awt.Color(255, 255, 255));
        btn_validate.setText("Confirmer");
        btn_validate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_validateActionPerformed(evt);
            }
        });

        pDate.setBackground(new java.awt.Color(242, 242, 242));
        pDate.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        pDate.setText("Date*");
        pDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pDateActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Rendez-vous");

        pHour.setBackground(new java.awt.Color(242, 242, 242));
        pHour.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        pHour.setText("Heure*");
        pHour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pHourActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pBirthDate)
                        .addGap(330, 330, 330))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 495, Short.MAX_VALUE)
                        .addComponent(btn_validate, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(pFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                            .addComponent(pDate)
                            .addComponent(pEmail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 113, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pTelephone, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                            .addComponent(pLastName, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                            .addComponent(pHour))
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(27, 27, 27)
                                .addComponent(choice_doctor, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pDate, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pHour, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pBirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(choice_doctor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_validate, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pFirstNameActionPerformed

    private void pLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pLastNameActionPerformed

    private void pEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pEmailActionPerformed

    private void pTelephoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pTelephoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pTelephoneActionPerformed

    private void pBirthDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pBirthDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pBirthDateActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void btn_validateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_validateActionPerformed
        
        ContellerAppointment controllerAppoitment = new ContellerAppointment();
        try {
            ModelPatient patient = new ModelPatient();
                patient.setFirstName(pFirstName.getText().strip());
                patient.setLastName(pLastName.getText().strip());
                patient.setEmail(pEmail.getText().strip());
                patient.setTelephone(pTelephone.getText().strip());
                patient.setBirthDate(pBirthDate.getText().strip());
                
                System.out.println(pBirthDate.getText().strip());
                
            String doctor = choice_doctor.getSelectedItem();
            String date = pDate.getText().strip();
            String hour = pHour.getText().strip();
            
            controllerAppoitment.createAppointementWith(patient, doctor, date, hour);
        } catch (SQLException ex) {
            Logger.getLogger(PanelForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_validateActionPerformed

    private void pDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pDateActionPerformed

    private void pHourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pHourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pHourActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private assets.swing.Button btn_cancel;
    private assets.swing.Button btn_validate;
    private java.awt.Choice choice_doctor;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField pBirthDate;
    private javax.swing.JTextField pDate;
    private javax.swing.JTextField pEmail;
    private javax.swing.JTextField pFirstName;
    private javax.swing.JTextField pHour;
    private javax.swing.JTextField pLastName;
    private javax.swing.JTextField pTelephone;
    // End of variables declaration//GEN-END:variables

}
