package main.components.appointement;

import java.awt.Color;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.Dictionary;
import java.util.logging.Level;
import java.util.logging.Logger;
import main.components.Message;
import main.controller.ControllerFacture;
import main.model.ModelStatus;
import main.views.MainView;

/**
 *
 * @author malco
 */
public class PanelView extends javax.swing.JPanel {
    
    private final MainView grandParent;
    
    private boolean generateFactureButtonIsActive;
    private final int appoitementID;
    
    /**
     * Creates new form PanelView
     * @param grandParent
     * @param commande_back
     * @param infos
     */
    public PanelView(MainView grandParent, ActionListener commande_back, Dictionary infos) {
        initComponents();
        
        this.grandParent = grandParent;
        appoitementID = Integer.parseInt(infos.get("id").toString());
        generateFactureButtonIsActive = true;
        
        try {
            boolean factureIsExist = ControllerFacture.verifieIfExistByAppoitementID(appoitementID);
            
            ModelStatus modelStatus = new ModelStatus();
            modelStatus.setDesabled();
            
            if(modelStatus.getStatus().equals(infos.get("status").toString()) || factureIsExist) {
                deactivateGenerateFactureButton();
            }
        } catch (SQLException ex) {
            grandParent.showMessage(Message.MessageType.ERROR, "Error: à verification facture");
            Logger.getLogger(PanelView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        setInfos(infos);
        initCommandeBack(commande_back);
    }
    
    private void initCommandeBack(ActionListener commande_back) {
        btn_cancel.addActionListener(commande_back);
    }
    
    private void deactivateGenerateFactureButton() {
        generateFactureButtonIsActive = false;
        cmd_createFacture.setBackground(new Color(134,183,157));
    }
    
    private void setInfos(Dictionary infos) {
        rdvIdText.setText("N°"+infos.get("id").toString());
        dateText.setText(infos.get("date").toString());
        hourText.setText(infos.get("hour").toString());

        patientFullNameText.setText(infos.get("patientFirstName").toString()+" "+infos.get("patientLastName").toString());
        patientIdText.setText(infos.get("patientID").toString());
        patientEmailText.setText(infos.get("patientEmail").toString());
        patientTelText.setText(infos.get("patientTel").toString());

        doctorNameText.setText(infos.get("doctorName").toString());
        doctorIdText.setText(infos.get("doctorID").toString());
        doctorEmailText.setText(infos.get("doctorEmail").toString());
        doctorTelText.setText(infos.get("doctorTel").toString());

        rdvReaisonText.setText(infos.get("reason").toString());
        rdvStatus.setText(infos.get("status").toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dateText = new javax.swing.JLabel();
        hourText = new javax.swing.JLabel();
        patientFullNameText = new javax.swing.JLabel();
        patientIdText = new javax.swing.JLabel();
        patientEmailText = new javax.swing.JLabel();
        doctorNameText = new javax.swing.JLabel();
        rdvReaisonText = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        patientTelText = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        doctorIdText = new javax.swing.JLabel();
        doctorEmailText = new javax.swing.JLabel();
        doctorTelText = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        rdvIdText = new javax.swing.JLabel();
        cmd_createFacture = new assets.swing.Button();
        btn_cancel = new assets.swing.Button();
        jLabel8 = new javax.swing.JLabel();
        rdvStatus = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel1.setText("Le");

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel2.setText("à ");

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel3.setText("De :");

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel4.setText("Avec le docteur :");

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel5.setText("A raison de :");

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel6.setText("Téléphone :");

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel7.setText("Email :");

        dateText.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        dateText.setText("Date");

        hourText.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        hourText.setText("Heure");

        patientFullNameText.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        patientFullNameText.setText("Nom Prénom");

        patientIdText.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        patientIdText.setText("id");

        patientEmailText.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        patientEmailText.setText("email");

        doctorNameText.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        doctorNameText.setText("nom");

        rdvReaisonText.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        rdvReaisonText.setText("raison");

        jLabel15.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel15.setText("id :");

        patientTelText.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        patientTelText.setText("tel");

        jLabel17.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel17.setText("id :");

        jLabel18.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel18.setText("Email :");

        jLabel19.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel19.setText("Téléphone :");

        doctorIdText.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        doctorIdText.setText("jLabel20");

        doctorEmailText.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        doctorEmailText.setText("jLabel21");

        doctorTelText.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        doctorTelText.setText("jLabel22");

        jLabel23.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel23.setText("Rendez-vous");

        rdvIdText.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        rdvIdText.setText("rdv_id");

        cmd_createFacture.setBackground(new java.awt.Color(35, 166, 97));
        cmd_createFacture.setForeground(new java.awt.Color(255, 255, 255));
        cmd_createFacture.setText("Générez la facture");
        cmd_createFacture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_createFactureActionPerformed(evt);
            }
        });

        btn_cancel.setBackground(new java.awt.Color(242, 242, 242));
        btn_cancel.setText("Retour");

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel8.setText("Statut :");

        rdvStatus.setText("jLabel9");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(patientIdText))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(patientEmailText))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(patientTelText))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(doctorTelText))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(doctorEmailText))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(doctorIdText))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmd_createFacture, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(130, 130, 130))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(patientFullNameText)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(doctorNameText)
                        .addGap(730, 730, 730))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdvReaisonText)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdvStatus))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdvIdText)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hourText)
                        .addGap(27, 27, 27))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(dateText)
                    .addComponent(hourText)
                    .addComponent(jLabel23)
                    .addComponent(rdvIdText))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(patientFullNameText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(patientIdText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(patientEmailText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(patientTelText))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(doctorNameText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(doctorIdText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(doctorEmailText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(doctorTelText))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rdvReaisonText)
                    .addComponent(jLabel8)
                    .addComponent(rdvStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmd_createFacture, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmd_createFactureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_createFactureActionPerformed
        if(generateFactureButtonIsActive) {
            try {
                ControllerFacture.generateFactureForAppoitement(appoitementID);
                deactivateGenerateFactureButton();
                grandParent.showMessage(Message.MessageType.SUCCESS, "Facture générée");
            } catch (SQLException ex) {
                grandParent.showMessage(Message.MessageType.ERROR, "Erreur lors de la gérérationde la facture");
                Logger.getLogger(PanelView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_cmd_createFactureActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private assets.swing.Button btn_cancel;
    private assets.swing.Button cmd_createFacture;
    private javax.swing.JLabel dateText;
    private javax.swing.JLabel doctorEmailText;
    private javax.swing.JLabel doctorIdText;
    private javax.swing.JLabel doctorNameText;
    private javax.swing.JLabel doctorTelText;
    private javax.swing.JLabel hourText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel patientEmailText;
    private javax.swing.JLabel patientFullNameText;
    private javax.swing.JLabel patientIdText;
    private javax.swing.JLabel patientTelText;
    private javax.swing.JLabel rdvIdText;
    private javax.swing.JLabel rdvReaisonText;
    private javax.swing.JLabel rdvStatus;
    // End of variables declaration//GEN-END:variables
}
