package main.components.login;

import assets.swing.Button;
import assets.swing.MyPasswordField;
import assets.swing.MyTextField;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author malco
 */
public class PanelLogin extends javax.swing.JPanel {
    
    private String email = "";
    private String password = "";

    public String getEmail() {
        return email;
    }

    public String getPassword() {
        return password;
    }
     
    
    private final Color backgroundColor = new Color(255, 255, 255);
    private final Color buttonForegroundColor = new Color(250,250,250);
    private final Color textColor = new Color(35, 166, 97);
    private final int iconSize = 20;
    private final int fieldSize = 60;
    
    private MyTextField txt_email;
    private MyPasswordField txt_password;
    private Button loginButton;
    
    public PanelLogin(ActionListener loginEvent) {
        initComponents();
        init(loginEvent);
        manageLoginCommand();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void init(ActionListener loginCommande){
        initLayout();
        initEmailField();
        initPasswordField();
        initLoginButton(loginCommande);
    }
    
    private void initLayout()
    {
        this.setLayout(new MigLayout("wrap", "push[center]push", "push[]25[]10[]25[]push"));
        JLabel label = new JLabel("Se connecter");
        label.setFont(new Font("sansserif", 1, 30));
        label.setForeground(textColor);
        this.add(label);
    }
    
    private void initEmailField()
    {
        txt_email = new MyTextField();
        ImageIcon icon_email = new ImageIcon(getClass().getResource("/assets/icons/envelope.png"));
        Image resizedUserImage = icon_email.getImage().getScaledInstance(iconSize, iconSize, Image.SCALE_SMOOTH);
        ImageIcon new_user_icon = new ImageIcon(resizedUserImage);
        txt_email.setPrefixIcon(new_user_icon);
        txt_email.setHint("E-mail");
        this.add(txt_email, "w " + fieldSize + "%");
    }
    
    private void initPasswordField()
    {
        txt_password = new MyPasswordField();
        ImageIcon icon_password = new ImageIcon(getClass().getResource("/assets/icons/key.png"));
        Image resizedPasswordImage = icon_password.getImage().getScaledInstance(iconSize, iconSize, Image.SCALE_SMOOTH);
        ImageIcon new_password_icon = new ImageIcon(resizedPasswordImage);
        txt_password.setPrefixIcon(new_password_icon);
        txt_password.setHint("Mot de passe");
        this.add(txt_password, "w " + fieldSize + "%");
    }
    
    private void initLoginButton(ActionListener loginCommande){
        loginButton = new Button();
        loginButton.setBackground(textColor);
        loginButton.setForeground(buttonForegroundColor);
        loginButton.addActionListener(loginCommande);
        loginButton.setText("Connection");
        this.add(loginButton, "w 40%, h 40");
    }
    
    private void manageLoginCommand()
    {
        loginButton.addActionListener((ActionEvent e) -> {
            email = txt_email.getText().trim();
            password = String.valueOf(txt_password.getPassword());
        });
    }
    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D graphics2D = (Graphics2D) g;
        graphics2D.setPaint(backgroundColor);
        graphics2D.fillRect(0, 0, getWidth(), getHeight());
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
