package main.views;

import main.components.facture.PanelList;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author malco
 */
public class PanelFacture extends javax.swing.JPanel {

    /**
     * Creates new form PanelFacture
     */
    public PanelFacture() {
        initComponents();
        
        MigLayout layout = new MigLayout("fill, insets 0");
        scene.setLayout(layout);
        
        PanelList FactureList = new PanelList();
         scene.add(FactureList);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HeandPane = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        scene = new javax.swing.JPanel();

        setOpaque(false);

        HeandPane.setBackground(new java.awt.Color(35, 211, 137));
        HeandPane.setPreferredSize(new java.awt.Dimension(965, 115));

        jLabel11.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Factures");

        javax.swing.GroupLayout HeandPaneLayout = new javax.swing.GroupLayout(HeandPane);
        HeandPane.setLayout(HeandPaneLayout);
        HeandPaneLayout.setHorizontalGroup(
            HeandPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeandPaneLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel11)
                .addContainerGap())
        );
        HeandPaneLayout.setVerticalGroup(
            HeandPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeandPaneLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel11)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        scene.setBackground(new java.awt.Color(255, 255, 255));
        scene.setOpaque(false);

        javax.swing.GroupLayout sceneLayout = new javax.swing.GroupLayout(scene);
        scene.setLayout(sceneLayout);
        sceneLayout.setHorizontalGroup(
            sceneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sceneLayout.setVerticalGroup(
            sceneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 477, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HeandPane, javax.swing.GroupLayout.DEFAULT_SIZE, 977, Short.MAX_VALUE)
            .addComponent(scene, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(HeandPane, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(scene, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HeandPane;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel scene;
    // End of variables declaration//GEN-END:variables
}
