package main.components.facture;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.ActionListener;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.SQLException;
import java.util.Dictionary;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import main.components.Message;
import main.controller.ControllerFacture;
import main.views.MainView;

/**
 *
 * @author malco
 */
public class PanelView extends javax.swing.JPanel {

    MainView grandParent;
            
    private final Dictionary factureData;
    private final int factureID;
    private boolean  payFactureCmdIsActive;
    
    /**
     * Creates new form PanelView
     * @param grandParent
     * @param factureData
     * @param commande_back
     */
    public PanelView(MainView grandParent, Dictionary factureData, ActionListener commande_back) {
        initComponents();
        
        this.grandParent = grandParent;
        
        btn_cancel.addActionListener(commande_back);
        this.factureData = factureData;
        
        
        payFactureCmdIsActive = true;
        factureID = Integer.parseInt(factureData.get("factureID").toString());
        
        clientFullName.setText(factureData.get("patientFirstName").toString()+" "+factureData.get("patientLastName").toString());
        clientTel.setText(factureData.get("patientTel").toString());
        clientEmail.setText(factureData.get("patientEmail").toString());
        
        factureIDText.setText(factureData.get("factureID").toString());
        factureDate.setText(factureData.get("date").toString());
        serviceID.setText(factureData.get("serviceID").toString());
        
        priceTotal.setText(factureData.get("price").toString()+" Ar");
        
        if(Boolean.parseBoolean(factureData.get("isPaid").toString())){
            isPaidText.setText("Oui");
            deactivateCmdPayBtn();
        } else {
            isPaidText.setText("Non");
        }
        
        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
        tableModel.addRow(new Object[]{ 
                factureData.get("appoitmentID"),
                factureData.get("appoitmentDate"),
                factureData.get("appointmentHour"),
                factureData.get("reason"),
                factureData.get("doctor"), 
                factureData.get("price")
            });
    }
    
    private void deactivateCmdPayBtn() {
        payFactureCmdIsActive = false;
        cmdPay.setBackground(new Color(134,183,157));
    }
    
    private void print(JPanel panel) {
        PrinterJob printerJob = PrinterJob.getPrinterJob();
        printerJob.setJobName("Print facture");
        
        printerJob.setPrintable(new Printable() {
            @Override
            public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
                if (pageIndex > 0) {
                    return Printable.NO_SUCH_PAGE;
                }
                Graphics2D graphics2D = (Graphics2D)graphics;
                graphics2D.translate(pageFormat.getImageableX()*2, getAlignmentY()*2);
                graphics2D.scale(0.63, 0.7);
                panel.paint(graphics2D);
                return Printable.PAGE_EXISTS;
            }
        });
        
        boolean returningResult = printerJob.printDialog();
        if(returningResult) {
            try {
                printerJob.print();
            } catch (PrinterException printerException) {
                JOptionPane.showMessageDialog(this, "Print error: "+printerException.getMessage());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_cancel = new assets.swing.Button();
        cmdPay = new assets.swing.Button();
        printablePanel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        priceTotal = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        isPaidText = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        clientFullName = new javax.swing.JLabel();
        clientTel = new javax.swing.JLabel();
        clientEmail = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        factureIDText = new javax.swing.JLabel();
        factureDate = new javax.swing.JLabel();
        serviceID = new javax.swing.JLabel();
        cmdPrint = new assets.swing.Button();

        setBackground(new java.awt.Color(255, 255, 255));

        btn_cancel.setBackground(new java.awt.Color(242, 242, 242));
        btn_cancel.setText("Retour");

        cmdPay.setBackground(new java.awt.Color(35, 166, 97));
        cmdPay.setForeground(new java.awt.Color(255, 255, 255));
        cmdPay.setText("Payer");
        cmdPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdPayActionPerformed(evt);
            }
        });

        printablePanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setFont(new java.awt.Font("Yu Gothic Light", 1, 24)); // NOI18N
        jLabel13.setText("Facture");

        priceTotal.setFont(new java.awt.Font("Yu Gothic Light", 1, 18)); // NOI18N
        priceTotal.setText("Prix en Ar");

        jLabel4.setFont(new java.awt.Font("Yu Gothic Light", 1, 18)); // NOI18N
        jLabel4.setText("TOTAL");

        isPaidText.setFont(new java.awt.Font("Yu Gothic Light", 1, 18)); // NOI18N
        isPaidText.setText("Non");

        jPanel8.setBackground(new java.awt.Color(35, 166, 97));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 105, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jLabel5.setFont(new java.awt.Font("Yu Gothic Light", 1, 18)); // NOI18N
        jLabel5.setText("Payée");

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        jLabel9.setText("DE");

        clientFullName.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 12)); // NOI18N
        clientFullName.setText("Nom Prénom");

        clientTel.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 12)); // NOI18N
        clientTel.setText("Tél");

        clientEmail.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 12)); // NOI18N
        clientEmail.setText("Email");

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        jLabel10.setText("FACTURE N°");

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        jLabel11.setText("DATE");

        jLabel14.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        jLabel14.setText("SERVICE N°");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rendez-vous N°", "Date", "Heure", "Raison", "Docteur", "Prix"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(40);
        jTable1.setSelectionBackground(new java.awt.Color(35, 211, 137));
        jTable1.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTable1);

        factureIDText.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 12)); // NOI18N
        factureIDText.setText("fact num");

        factureDate.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 12)); // NOI18N
        factureDate.setText("date facture");

        serviceID.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 12)); // NOI18N
        serviceID.setText("service id");

        javax.swing.GroupLayout printablePanelLayout = new javax.swing.GroupLayout(printablePanel);
        printablePanel.setLayout(printablePanelLayout);
        printablePanelLayout.setHorizontalGroup(
            printablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(printablePanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(printablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(printablePanelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(isPaidText, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(printablePanelLayout.createSequentialGroup()
                        .addGroup(printablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clientEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(676, 676, 676))
                    .addGroup(printablePanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(priceTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, printablePanelLayout.createSequentialGroup()
                        .addGroup(printablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(printablePanelLayout.createSequentialGroup()
                                .addComponent(clientTel, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel14))
                            .addGroup(printablePanelLayout.createSequentialGroup()
                                .addComponent(clientFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11))
                            .addGroup(printablePanelLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10)))
                        .addGap(53, 53, 53)
                        .addGroup(printablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(factureIDText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(factureDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(serviceID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(6, 6, 6))
            .addGroup(printablePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        printablePanelLayout.setVerticalGroup(
            printablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(printablePanelLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addGap(12, 12, 12)
                .addGroup(printablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(factureIDText)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(printablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientFullName)
                    .addComponent(factureDate)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(printablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientTel)
                    .addComponent(serviceID)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clientEmail)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(printablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(priceTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(printablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(isPaidText))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        cmdPrint.setForeground(new java.awt.Color(255, 0, 51));
        cmdPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/download.png"))); // NOI18N
        cmdPrint.setText("Imprimer");
        cmdPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(printablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmdPay, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(236, 236, 236))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmdPrint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(cmdPrint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(printablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdPay, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmdPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdPrintActionPerformed
        print(printablePanel);
    }//GEN-LAST:event_cmdPrintActionPerformed

    private void cmdPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdPayActionPerformed
        if(payFactureCmdIsActive) {
            try {
                ControllerFacture.pay(factureID);
                deactivateCmdPayBtn();
                grandParent.showMessage(Message.MessageType.SUCCESS, "Facture payée");
            } catch (SQLException ex) {
                grandParent.showMessage(Message.MessageType.ERROR, "Erreur: payement facture");
                Logger.getLogger(PanelView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_cmdPayActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private assets.swing.Button btn_cancel;
    private javax.swing.JLabel clientEmail;
    private javax.swing.JLabel clientFullName;
    private javax.swing.JLabel clientTel;
    private assets.swing.Button cmdPay;
    private assets.swing.Button cmdPrint;
    private javax.swing.JLabel factureDate;
    private javax.swing.JLabel factureIDText;
    private javax.swing.JLabel isPaidText;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel priceTotal;
    private javax.swing.JPanel printablePanel;
    private javax.swing.JLabel serviceID;
    // End of variables declaration//GEN-END:variables
}
