package assets.swing.cell.cc;

import java.awt.event.ActionEvent;

/**
 *
 * @author malco
 */
public class PanelActionCC extends javax.swing.JPanel {

    /**
     * Creates new form PanelAction
     */
    public PanelActionCC() {
        initComponents();
    }
    
    public void initEvent(TableActionEventCC event, int row) {
        cmdComplete.addActionListener((ActionEvent ae) -> {
            event.onComplete(row);
        });
        cmdCancel.addActionListener((ActionEvent ae) -> {
            event.onCancel(row);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmdComplete = new assets.swing.cell.ActionButton();
        cmdCancel = new assets.swing.cell.ActionButton();

        cmdComplete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/check.png"))); // NOI18N

        cmdCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/cross-small.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmdCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmdComplete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmdComplete, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private assets.swing.cell.ActionButton cmdCancel;
    private assets.swing.cell.ActionButton cmdComplete;
    // End of variables declaration//GEN-END:variables
}
